version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: diabetbot
      POSTGRES_USER: diabetbot
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diabetbot"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=diabetbot
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=diabetbot
      - DB_SSLMODE=disable
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_WEBHOOK_URL=${TELEGRAM_WEBHOOK_URL}
      - WEBAPP_URL=${WEBAPP_URL}
      - GIGACHAT_API_KEY=${GIGACHAT_API_KEY}
      - GIGACHAT_BASE_URL=https://gigachat.devices.sberbank.ru/api/v1
      - SERVER_PORT=8080
      - SERVER_HOST=0.0.0.0
      - ENVIRONMENT=production
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs

  caddy:
    image: caddy:2.7.4
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

volumes:
  postgres_data: